---
# VPS initial setup playbook for Shift Planning deployment
# Uses role-based architecture for clean, maintainable infrastructure setup

- name: Setup VPS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display start message
      debug:
        msg: |
          Starting VPS setup for Shift Planning...
          This will install system packages, configure SSH, and clone the repository.

- name: Configure VPS System and Infrastructure
  hosts: all
  become: yes
  roles:
    - role: vps_setup
      tags: ["vps_setup", "packages"]

    - role: firewall
      tags: ["vps_setup", "firewall"]

- name: Setup Git SSH Keys
  hosts: all
  become: yes
  tasks:
    - name: Setup SSH keys for Git access
      include_role:
        name: git_repository
      tags: ["vps_setup", "git", "ssh-setup"]

- name: Post-setup tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display completion message
      debug:
        msg: |
          ================================================
          VPS setup for Shift Planning completed successfully!
          ================================================

          Completed tasks:
          ✓ System packages installed (Podman, Node.js, Git, HAProxy, Firewalld)
          ✓ SSH keys configured for Git repository access
          ✓ Firewall configured

          ⚠️  IMPORTANT: Next steps required before deployment:

          1. Add the SSH public key to GitHub:
             - Go to each repository's Settings -> Deploy keys -> Add deploy key
             - Copy the public key shown above
             - Title: VPS Deploy Key ({{ ansible_hostname | default('vps') }})
             - Paste the key and save
             - Read-only access is sufficient

          2. Clone all repositories:
             ansible-playbook playbooks/manage-repositories.yml -i inventories/{{ deployment_environment }}/hosts.yml

          3. Deploy HAProxy (optional):
             ansible-playbook deploy-haproxy.yml -i inventories/{{ deployment_environment }}/hosts.yml --ask-vault-pass

          4. Deploy application services:
             ansible-playbook deploy-services.yml -i inventories/{{ deployment_environment }}/hosts.yml --ask-vault-pass

          Available tags:
          - --tags "vps_setup"  : Run all VPS setup tasks
          - --tags "packages"   : Only install system packages
          - --tags "ssh-setup"  : Only setup SSH keys
          - --tags "firewall"   : Only configure firewall
