---
all:
  hosts:
    prod-server:
      ansible_host: # TODO: Replace with actual production server IP/hostname
      ansible_user: # TODO: Replace with actual SSH user
      ansible_ssh_private_key_file: # TODO: Replace with path to SSH private key
